### PR TITLE
Replaced ATZ with AT^RESET for the reset_modem Function

### PR DESCRIPTION
**Pull request by genesis2600**
Changed the reset command, to AT^RESET like we agreed on yesterday.

### CODE REVIEW

**Review by fontanon — CHANGES_REQUESTED** [review]
Hi @genesis2600 thanks for this. I've some requirements before approving this.

First, considering the commit is to change the GSMModem abstract class (which should only include Hayes AT commands) ... can you provide evidence AT^RESET is part of the common Hayes AT set? I've my reservations! Otherwise, please just add the command on the specific subclass.

Second, the ATZ command is still useful, I do not think we should replace it with RESET. Please,  rename it as something like "restore_settings", and add the RESET command as well.

**Comment by genesis2600** [comment]
Hello @fontanon, 
This is indeed an oversight from my part. The AT^RESET command is not part of the Hayes command set. I changed the concerned section back to its original state, did however, as requested, change the function name. I would now after reading the 3GPP TS 27.007 V16.2.0 documentation, also agree that the command might be useful as it resets the modem to its default values.

I also added a new function into the Huawei specific part which does an electric reset, which might be better adapted for certain situations, using the AT^RESET command. You can find the command in the Huawei AT Command Interface Specification under section 10.16.

**Comment by genesis2600** [comment]
My bad, seems like I approved the change myself...

**Comment by fontanon** [comment]
No worries, congrats!

**Pull request merged**
